// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace bank_core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404130035_InitTables")]
    partial class InitTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankRegistryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_url");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_id");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BankName")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_registry_bank_name");

                    b.ToTable("bank_registry", (string)null);
                });

            modelBuilder.Entity("MonetaryPolicyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DecisionUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision_url");

                    b.Property<DateTime?>("DeprecatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deprecated_at");

                    b.Property<decimal>("Inflation")
                        .HasColumnType("numeric")
                        .HasColumnName("inflation");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<decimal>("KeyRate")
                        .HasColumnType("numeric")
                        .HasColumnName("key_rate");

                    b.Property<decimal>("ReserveRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("reserve_ratio");

                    b.Property<decimal>("TotalMoneySupply")
                        .HasColumnType("numeric")
                        .HasColumnName("total_money_supply");

                    b.HasKey("Id");

                    b.ToTable("monetary_policy", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
